---
# tasks file for postgresql
  - name: Add PostgreSQL official APT repository
    sudo: yes
    apt_repository:
      repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ansible_distribution_release}}-pgdg main"
    tags:
      - postgresql
      - db
      - repo

  - name: Install PostgreSQL
    when: ansible_os_family == 'Debian'
    sudo: yes
    apt:
      name: "postgresql-{{postgresql_version}}"
      state: present
      force: yes
      update_cache: yes
      cache_valid_time: 3600
    tags:
      - postgresql
      - db
      - deps

  - name: ensure database is created
    postgresql_db: name={{dbname}}
                   encoding={{encoding}}
                   lc_collate={{locale}}
                   lc_ctype={{locale}}
                   template='template0'
    sudo: yes
    sudo_user: postgres

  - name: ensure user has access to database
    postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL
    sudo: yes
    sudo_user: postgres
    ignore_errors: yes

  - name: ensure user does not have unnecessary privilege
    postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB
    sudo: yes
    sudo_user: postgres
    ignore_errors: yes