---
# tasks file for postgresql
  - name: install prerequisites
    apt: name={{ item }} state=installed
    with_items:
      - postgresql
      - libpq-dev
      - python-psycopg2
    tags:
      - packages

  - name: ensure database is created
    postgresql_db: name={{dbname}}
                   encoding={{encoding}}
                   lc_collate={{locale}}
                   lc_ctype={{locale}}
                   template='template0'
    sudo: yes
    sudo_user: postgres

  - name: ensure user has access to database
    postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL
    sudo: yes
    sudo_user: postgres
    ignore_errors: yes

  - name: ensure user does not have unnecessary privilege
    postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB
    sudo: yes
    sudo_user: postgres
    ignore_errors: yes