---
  # Install mongodb from the 10gen repository
  - name: Add the Apt-key for the 10gen repository
    apt_key: id=7F0CEB10 url=http://docs.mongodb.org/10gen-gpg-key.asc

  - name: Add the Apt-repository
    apt_repository: repo="deb http://repo.mongodb.org/apt/debian wheezy/mongodb-org/3.0 main" state=present update_cache=yes

  - name: Install MongoDB Packages and requirements
    apt: pkg={{ item }} state=present force=yes
    with_items:
      - mongodb-org
