---
  - name: Add Nginx Repository
    apt_repository: repo='ppa:nginx/stable' state=present
    register: ppastable

  - name: Install Nginx
    apt: pkg=nginx state=installed update_cache=true
    when: ppastable|success

  - name: Drop updated nginx.conf file
    copy: src=nginx.conf dest=/etc/nginx/nginx.conf owner=root group=root mode=644

  - name: Add proxy settings file
    copy: src=proxy.conf dest=/etc/nginx/conf.d/proxy.conf owner=root group=root mode=644

  - name: Remove Default Site Configuration
    file: path=/etc/nginx/sites-enabled/default state=absent

  - name: Start Nginx
    service: name=nginx state=started
