---
  - name: add NodeSource repository for Node.js 4.0 (deb)
    apt_repository: repo='deb https://deb.nodesource.com/node_4.x {{ ansible_distribution_release|lower }} main' state=present
    when: (nodejs_version is defined)  and  nodejs_version|version_compare('4.0', '>=')

  - name: install Node.js with specific version
    apt: name={{ item }}  update_cache=yes  state=present force=yes
    with_items: [ "nodejs={{ nodejs_version }}*" ]
    when: nodejs_version is defined

  # - name: Create symlink for legacy code node->nodejs
  #   file: src=/usr/bin/nodejs dest=/usr/local/bin/node state=link